// script.js

// Liste der zufälligen Dates, die du selbst geschrieben hast
const texts = [
  "Picknick im Park mit selbstgemachtem Essen",
"Wandern in den Bergen oder einem schönen Waldgebiet",
"Fahrrad-Tour durch die Stadt oder Natur",
"Kanufahren oder Tretbootfahren auf einem See",
"Besuch eines botanischen Gartens oder Zoos",
"Sternenhimmel beobachten mit einer Decke und Snacks",
"Spaziergang am Strand oder Flussufer bei Sonnenuntergang",
"Geocaching-Abenteuer in eurer Umgebung",
"Besuch eines Abenteuergolf- oder Minigolf-Platzes",
"Schlittschuhlaufen im Winter (oder Rollschuhlaufen im Sommer)",
"Ein Outdoor-Konzert oder Festival besuchen",
"Blumen pflücken auf einer Wiese oder in einem Blumenfeld",
"Drachen steigen lassen an einem windigen Tag",
"Ein Tierheim besuchen und mit Hunden Gassi gehen",
"Eine Grillparty oder Lagerfeuer mit Stockbrot organisieren",
"Einen Aussichtspunkt erklimmen und die Stadt von oben sehen",
"Gemeinsam einen Malkurs oder Töpferkurs besuchen",
"DIY-Projekte zusammen basteln (z.B. Holzarbeiten, Schmuck)",
"Ein Puzzle mit vielen Teilen zusammenlegen",
"Backen von Keksen oder einer Torte und sie dekorieren",
"Gemeinsames Kochen eines neuen oder exotischen Gerichts",
"Ein eigenes Kunstwerk malen mit Farben und Leinwand",
"Ein DIY-Fotobuch oder Scrapbook erstellen",
"Karaoke-Abend zu Hause oder in einer Karaoke-Bar",
"Ein gemeinsames Musikstück komponieren oder ein Cover singen",
"Ein Tanzkurs für Salsa, Tango oder Walzer buchen",
"Ein Escape-Room-Abenteuer machen (online oder vor Ort)",
"Videos oder TikToks drehen, die euch Spaß machen",
"Ein Buch oder Hörbuch gemeinsam lesen und darüber reden",
"Film- oder Serienmarathon mit Decken und Popcorn",
"Spa-Tag zu Hause mit Gesichtsmasken und Massagen",
"Ein Café-Hopping-Abenteuer (verschiedene Cafés ausprobieren)",
"Brettspiel-Abend mit euren Lieblingsspielen",
"Gemeinsames Yoga oder eine Meditation ausprobieren",
"Frühstück im Bett zubereiten und genießen",
"Einen ruhigen Tag in der Bibliothek oder Buchhandlung verbringen",
"Ein Home-Planetarium mit Sternenprojektor aufbauen",
"Alte Fotos anschauen und Erinnerungen teilen",
"Indoor-Klettern oder Bouldern ausprobieren",
"Paintball oder Lasertag spielen",
"Trampolinpark besuchen und euch austoben",
"Go-Kart fahren auf einer Rennstrecke",
"Eine Achterbahn im Freizeitpark testen",
"Ziplining oder einen Hochseilgarten besuchen",
"Bogenschießen oder Axtwerfen ausprobieren",
"Escape-Room-Rätsel lösen",
"Eine spontane Reise oder einen Tagesausflug planen",
"Gemeinsam auf eine Schnitzeljagd gehen",
"Ein Restaurant besuchen, das ihr noch nie ausprobiert habt",
"Einen Foodtruck-Markt erkunden",
"Einen Kochkurs für eine neue Küche buchen (z.B. Thai, Italienisch)",
"Eine Schokoladen- oder Weinverkostung machen",
"Eure eigenen Cocktails mixen und verkosten",
"Ein Candlelight-Dinner zu Hause vorbereiten",
"Sushi selber machen und rollen",
"Frühstück oder Brunch in einem besonderen Café genießen",
"Retro-Videospiele zusammen spielen (z.B. Mario Kart)",
"VR-Arcade oder virtuelle Spiele ausprobieren",
"Ein digitales Quiz oder Trivia-Spiel gemeinsam lösen",
"Einen Science-Fiction-Filmabend mit Snacks machen",
"Besuch eines Museums oder einer Kunstausstellung",
"Ein Theaterstück oder Musical besuchen",
"Ins Planetarium oder Naturkundemuseum gehen",
"Ein Live-Konzert oder eine Comedy-Show besuchen",
"Eine Stadtführung oder historische Tour buchen",
"Eine kleine Roadtrip-Tour mit guter Musik planen",
"Eine Stadt in der Nähe erkunden, die ihr noch nicht kennt",
"Eine Fahrt mit dem Zug ins Grüne machen",
"Eine Nacht in einem Baumhaus oder Tiny House verbringen",
"Eine Motto-Party zu zweit veranstalten (z.B. 80er-Jahre)",
"Eine Liste mit gemeinsamen Lebenszielen schreiben",
"Lustige Challenges ausprobieren (z.B. 'Wer kocht das beste Frühstück?')",
"Ein Spielzeugmodell zusammenbauen (z.B. Lego)",
"Einen Flohmarkt oder Antiquitätenmarkt durchstöbern",
"Ein Quiz über eure Beziehung erstellen und spielen",
"Ein gemeinsames Picknick bei Sonnenuntergang",
"Zusammen den Sonnenaufgang beobachten",
"Eine Bootsfahrt bei Nacht mit Kerzenschein machen",
"Ein 'Lichtermeer' aus Kerzen und Lichterketten zu Hause gestalten",
"Liebesbriefe oder Gedichte für einander schreiben und vorlesen",
"Gemeinsam eine neue Sprache ausprobieren (z.B. mit Apps wie Duolingo)",
"Eure Bucket List schreiben und besprechen",
"Blindverkostung von verschiedenen Snacks oder Getränken machen",
"Eine Comedy-Show oder einen Stand-up-Abend erleben"
];

// Event-Listener für den Button
document.getElementById("generateButton").addEventListener("click", function() {
  // Zufälligen Index auswählen
  const randomIndex = Math.floor(Math.random() * texts.length);
  
  // Den zufälligen Text in das Ausgabefeld schreiben
  document.getElementById("output").textContent = texts[randomIndex];
});
